<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AssemblyName>s3pi.ScriptResource</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CS System Classes\CS System Classes.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\..\Interfaces\Interfaces.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\..\Settings\Settings.csproj">
            <Private>False</Private>
        </ProjectReference>
    </ItemGroup>

</Project>
